sudo: required
services:
  - docker

before_install:
  - docker build -t ecomm:latest -f DockerFile.dev .

script:
  - docker run -e CI=true ecomm:latest npm run test -- --coverage

deploy:
  provider: heroku
  api_key: ...
  app: e-comm-live
  run: "npm start"
  strategy: git
  on:
    branch: master
